### ISSUE TITLE
Help with Assignments

### ISSUE THREAD

**Issue by omerlavian20** [ShawnTylerSchwartz/eeb-c177-w20#1]
I know we are not supposed to share data online, but, just so that I am 100% clear, is it some sort of breach of academic integrity to have help from non-classmate friends? The reason I ask is that I asked a minor question about today's assignment to a CS major friend of mine, so he saw my terminal briefly.

Sorry if this is a dumb question! I get very paranoid about making sure I'm not breaking rules.

**Comment by shawntz** [comment]
This policy refers more to the _unauthorized redistribution of materials_ to online sources as well as those not enrolled in this course (i.e., by sending them copies of materials and/or sharing your materials with them)--which is a standard policy at UCLA for all courses. I have attached the official policy below for reference @omerlavian20.

> Please remember that you are not allowed to upload or share any class content not created by you onto third-party sites and/or with anyone not enrolled in the course. The unauthorized redistribution which includes, but is not limited to, providing course materials such as the course syllabus, homework, examinations, course Power Points, and course notes, to online websites, commercial entities, and test banks without the consent of the course instructor may be considered a violation of Section 102.23/102:23a of the UCLA Student Conduct Code, and may result in disciplinary action, including but not limited to, suspension from the University.

In the future, I would recommend asking questions regarding the assignments on this discussion board in case any of your peers have the same question, so that all of you can benefit from each other. You are fine in this specific instance though.
