### ISSUE TITLE
Trouble Committing 

### ISSUE THREAD

**Issue by goharmihranian** [ShawnTylerSchwartz/eeb-c177-w20#10]
Hello!

So I finished my text file with my solutions: I added a folder named 1-16-20 to my class-assignments folder and created the text file for tomorrow's assignment in there.

after, I cd'd al the way into this folder and did:
git add -A
git commit -m "added commands and explanations to text file" 
git push origin master

It said done after I put my username and password and everything but when I check GitHub it's not there. 

Wondering why this is happening.

Thank you in advance!

**Comment by shawntz** [comment]
@goharmihranian I just looked at your GitHub repository for the class on your account and everything seemed as if it was there! Can you check again? Maybe there was a delay? Let me know!

**Comment by goharmihranian** [comment]
@ShawnTylerSchwartz It's there but now I'm wondering why there's a bunch of files before and after it. None of my previous commits are like this.

**Comment by shawntz** [comment]
@goharmihranian It looks like all of those files are the ones from the `data-shell` directory from the homework tutorial. It might be good to go through and clean up the directory by moving all of those files into the `1-16-20` directory, instead of the `class-assignments` parent directory. You can do this manually (drag-and-drop) within the file browser, or practice using the `mv` command in the terminal. Let me know if you have any questions about this in lecture this morning.
