### ISSUE TITLE
Homework #4 part 2 

### ISSUE THREAD

**Issue by alexphu1230** [ShawnTylerSchwartz/eeb-c177-w20#24]
Hi I try to add my homework #4 of the ExtractBodyM.sh script with my comments to my git and I keep getting this output. I looked online but can't figure out a way to fix it. Has anyone encountered this? Thank you!

"object file .git/objects/54/c4ca52b8e4175777b498fcbed5c2a68780abc5 is empty
error: object file .git/objects/54/c4ca52b8e4175777b498fcbed5c2a68780abc5 is empty
fatal: loose object 54c4ca52b8e4175777b498fcbed5c2a68780abc5 (stored in .git/objects/54/c4ca52b8e4175777b498fcbed5c2a68780abc5) is corrupt"

**Comment by goharmihranian** [comment]
I'm not sure what this means but I have having trouble getting it into the file through the terminal. I was following the steps but it wasn't showing up when I opened the file

**Comment by shawntz** [comment]
@alexphu1230 were you ever able to resolve this problem? If not, I can show you a few ways to solve it. Take a look at this issue though (https://github.com/ShawnTylerSchwartz/eeb-c177-w20/issues/5) which seems similar to the one that you may be experiencing and let me know what happens.

**Comment by shawntz** [comment]
@alexphu1230 after looking at your GitHub account I see you followed through with the steps to fix the repository as outlined in issue #5. Since that `.git-old` was a backup of the broken repository files, you can now delete `.git-old` from the repo folder using `rm -rf .git-old` to clean up your repo directory. I will close the issue now but feel free to re-open should any further issues persist.
