### ISSUE TITLE
fatal: The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by jpocon** [ShawnTylerSchwartz/eeb-c177-w20#28]
All -

Has anyone encountered this error during "git commit -m"? I tried committing my code and data last night/this morning (3GBs worth) and keep getting this error. After restarting, it says everything is up to date.

Is there a better way to commit large data sets?

J

**Comment by jpocon** [comment]
Sorry, update: it says everything is up to date, but jumping into github online, my code and data are nowhere to be found...

**Comment by shawntz** [comment]
@jpocon GitHub imposes strict upload limits so that each file is to be no larger than 100 MB (read more here: https://towardsdatascience.com/uploading-large-files-to-github-dbef518fa1a). I would recommend removing the large data files from your local GitHub repo directory and just pushing your analyses scripts. Offload the large files elsewhere (another local directory that is not part of your Git Repo, and just change the path within your Python code when loading in the file; i.e., `np.loadtxt(fname='~/path/to/large/datafile')`).

Let me know if you have any questions or issues with this.

**Comment by jpocon** [comment]
Great, make sense, thank you Shawn!
