### ISSUE TITLE
ExtractBodyM.sh Update

### ISSUE THREAD

**Issue by omerlavian20** [ShawnTylerSchwartz/eeb-c177-w20#31]
For making the command more dynamic, has anyone else run into the issue where it works fine for the Pacifici file but not for the other ones?

I get a new file with the name I make up in the command, but that csv file does not get formatted in the way that the Pacifici info did.

Thanks for your time!

**Comment by shawntz** [comment]
@omerlavian20 That is because the delimiters in the other two files that I posted are not the same as the delimiter that you "hard-coded" into your script (i.e., the **semicolon**). I would therefore recommend adding a third argument as part of your script to dynamically accept any delimiter.

Hint: when you call your bash script from the terminal, you should have the single quotes around the delimiter that you pass into the script as an argument. Post on here if you end up having trouble with this.

**Comment by omerlavian20** [comment]
Got it! Thanks a ton!
