### ISSUE TITLE
Issue Pushing HW5 P3 

### ISSUE THREAD

**Issue by goharmihranian** [ShawnTylerSchwartz/eeb-c177-w20#33]
I'm trying to push the assignment from lab today and am getting this message:

error: object file .git/objects/89/(bunch of letters and numbers) is empty 
error: object file .git/objects/89/(bunch of letters and numbers) is empty 
fatal: loose object 89(followed by the bunch of letters and numbers) is corrupt

I am just trying to push a jupyter notebook file like always but it isn't letting me. I didn't do anything differently

**Comment by shawntz** [comment]
Hmm @goharmihranian this is strange that this keeps happening to people -- and I'm not sure what is happening but I have a feeling it is has something to do with the virtual machines not shutting down properly. It seems similar to this issue (https://github.com/ShawnTylerSchwartz/eeb-c177-w20/issues/8), so check this out and see if this fixes things. Otherwise, I would manually migrate the information to a fresh local copy of the repository (which I can show you how to do in class tomorrow). 
**I would highly recommend making a physical backup copy of the files (i.e., going into your `eeb-c177-homework` local directory and copying the contents of your `lab-exercises` and `class-assignments` directories to a temporary local directory somewhere outside of the `eeb-c177-homework` directory (could be anywhere on the VM that you want.. just to be safe).**

**Comment by goharmihranian** [comment]
@ShawnTylerSchwartz I will come early to look over this with you because I don't want to mess anything up. I have a midterm after class so I will have to run right after. My other stuff pushed just fine, however

**Comment by shawntz** [comment]
@goharmihranian sounds good, and don't worry too much about it. This seems like a quick fix, however, if we aren't able to get it resolved in time, we can get it fixed later on as well.
