### ISSUE TITLE
Lab 5 HW Part 2 Question 5

### ISSUE THREAD

**Issue by Deap-Bhandal** [ShawnTylerSchwartz/eeb-c177-w20#35]
I am a little confused on what to do for question 5 on part 2. I understand it wants me to use a loop and the enumerate function, but I'm not sure what the output should be.

Should the output be the same as:
x = 5
coefs = [2, 4, 3]
y = coefs[0] * x**0 + coefs[1] * x**1 + coefs[2] * x**2
print(y)

which is 97

or does it want me to try each coef number and give an output for each of them?
Or something else?

**Comment by shawntz** [comment]
@Deap-Bhandal in essence, the output should be the same as the example given that the same original conditions were provided as in that example. The goal of this loop is to generalize it to any number of coefs provided, so that you don't have to fully write out `coefs[0] * x0 + coefs[1] * x1 + coefs[2] * x**2 ....`. Instead, you can iterate through a list of coefs provided and use the position along that list in each position as the power to raise the `x` value to.

**Comment by Deap-Bhandal** [comment]
Thank you!
