### ISSUE TITLE
Making Sure I Cloned the Book Correctly

### ISSUE THREAD

**Issue by omerlavian20** [ShawnTylerSchwartz/eeb-c177-w20#4]
So I just tried to clone the CSB repository and it looked like it worked. I then tried "ls" when that was done and saw the eeb-c177-homework repository that is on my Github account and then another one called "csb." Does that mean I did this right? Also, should I be seeing this repository as one of mine on my Github account because I don't currently.

**Comment by estmendoza** [comment]
Yes, you should see the **CSB** and **eeb-c177-homework** directories inside of repos. I don't think we should see CSB on Github because we haven't pushed anything to it yet.

**Comment by shawntz** [comment]
Thank you for responding @estmendoza. The first statement is correct. I would like add that you even though you have cloned (i.e., downloaded) the CSB repo from GitHub into your `~/Developer/repos` directory, you won't see CSB on your GitHub profile because that repository does not belong to you (ownership wise) and you have not created a repository on your own GitHub profile with that name. **Simply put, cloning another person's repository (that is not your own) merely downloads it to your computer, but does not link it to your GitHub.** 

Let me know if this clarifies things.

**Comment by omerlavian20** [comment]
Thank you both! That makes a lot of sense!
