### ISSUE TITLE
Homework #9 Running the script in shell

### ISSUE THREAD

**Issue by chausteven** [ShawnTylerSchwartz/eeb-c177-w20#51]
Hi, I got my function to run on Jupyter Notebook, but when I use the script as a .py file in shell I am not able to define the parameters of the function. The code "python datafunction.py" just gives me a blank output, but no error. Does anyone know how to fix this or if I am doing something wrong?

**Comment by shawntz** [comment]
@chausteven there are two ways to approach this. The **first** is to define the parameters of your function call within your script so that when you run the `.py` file, the script runs all the way through, top-to-bottom, with the values you have specified. The other, **second** option, is to utilize the inputs feature in Python that we learned in lecture to use the inputs of the user to fill in the values for the parameters of your function.

If you still have questions, please post a sample of your Python script file code to the forum so I can see what exactly it is that your code is trying to run. This will make it easier for me to give you more specific guidance.
