### ISSUE TITLE
cloning homework repo

### ISSUE THREAD

**Issue by robertreny** [ShawnTylerSchwartz/eeb-c177-w20#6]
Hi Shawn I'm having issues cloning the hwk repo in lab 1. I have /home/eebc177student/Developer/repos as my path. When I try to do git clone it asks me for username and password which I have tried to input but ultimately says that the repository is not found. I also tried to change the "username" term in //github.com/username/eeb-c177-homework.git to your username to no avail.

**Comment by shawntz** [comment]
Hi @robertreny, the reason you are running into errors are because that reference link that you are trying to clone is a template for the repository that you should have made on your own GitHub profile to store your homework in for this class. I just visited your profile and noticed that you have no repositories. Additionally, you cannot clone it from my account because I too do not have a repository with that name.

What you need to do first is create a repository on your own GitHub profile on the web using the "+" icon in the top-right corner of the screen. You should name this appropriately for your homework for this class. Then, you can clone it by doing `git clone https://github.com/robertreny/your-repository-name.git`.

Let me know if you're able to get this working.

**Comment by robertreny** [comment]
Thanks for the help Shawn. I got it working and started my food log last night.

**Comment by shawntz** [comment]
Okay great, thanks for letting me know @robertreny!
