### ISSUE TITLE
R Image Not properly showing on LaTex doc

### ISSUE THREAD

**Issue by soniavsd** [ShawnTylerSchwartz/eeb-c177-w20#61]
When I try to input my scatterplot from R (code: \includegraphics[width=\textwidth]{epi_envirohealth(location).pdf}\\) I get this image: 
![Screen Shot 2020-03-08 at 12 47 57 PM](https://user-images.githubusercontent.com/59575895/76169991-0ef31d80-613b-11ea-9bb8-56781f3ecbda.png)
What am I doing wrong??

**Comment by shawntz** [comment]
@soniavsd a separate LaTeX package may be required to load in PDFs. Instead, can you save a `jpeg` or `png` version of your figure from R and then load that in to you LaTeX document?

**Comment by soniavsd** [comment]
@ShawnTylerSchwartz I tried that but I got the exact same thing except it says jpeg and not pdf

**Comment by shawntz** [comment]
@soniavsd are you using the same code that you've been using before that worked? Is this on LaTeX on your computer or on Overleaf? Lastly, could it possibly be because there are `()` in the name of the file? Investigate the issue at hand and see if you can get it to work/give errors in a clean test document or make sure that there aren't any issues with the code that you've demoed with before that will for sure work (i.e., the code that we wrote in lab to perform these actions)

**Comment by soniavsd** [comment]
@ShawnTylerSchwartz Yes it is the same code, I edited the file name without parenthesis (now this: \includegraphics[width=\textwidth]{eco_envir_income.jpeg}) with the graphicx package in the beginning. I tried the same code on another doc and its not working on that one either.

**Comment by shawntz** [comment]
@soniavsd did you make sure to include `\usepackage{graphicx}` at the top of your `LaTeX` script? Also make sure that you include the graphics path `\graphicspath{{/figures}}` right below the `\usepackage{graphicx}` (and make sure that this is where the file to the figure that you're trying to load is in located). If this still doesn't work/fix the issue, can you email me a copy of your LaTeX file along with the figure so that I can try to reproduce the error myself? Thanks!

**Comment by soniavsd** [comment]
@ShawnTylerSchwartz i got it! I hadn't uploaded the entire pathway, thanks!
