### ISSUE TITLE
Alex Phu- Lightning Talk Presentation

### ISSUE THREAD

**Issue by alexphu1230** [ShawnTylerSchwartz/eeb-c177-w20#65]
Attached is my Lightning Talk Presentation: https://youtu.be/djBiAlX5p5w

**Comment by LinhN16** [comment]
Amazing presentation, Alex! The compilation of graphs in the end aided in the visualization of common trends seen with the diff forms of fuel consumption. I also agree with your analysis of diff fuel consumptions being a result of recent technological advancement; I wonder, if broken down and analyzed, what are the diff factors that may contribute to total CO2 emissions (i.e. what % of big companies are contributing to this?).

**Comment by jpocon** [comment]
Awesome overview, Alex! Enjoyed your deep dive into the data, and the inferences made from your visualizations. Lots of great questions for further investigation come to mind. I am more curious about any issues/or tips you have from building your function. I saw the import line of code was your first input ("In [1]"), then the actual function line was 60 inputs later ("In [61]"). What did you find during those 60 outputs that helped get you to the final function?

**Comment by jessicadeanda** [comment]
Great data visualization! Your plots clearly show the upward trend of CO2 emissions and fuel consuption over time. I think it would also be interesting to plot CO2 emissions vs total fuel consumption to see how the two variables are related.

**Comment by haonguyen318** [comment]
Hi Alex! I chose to focus on climate change for my project and within my data collection included data on CO2 emission in which I collected from Berkeley Earth so it's very interesting to see that you also chose the same topic! I liked how you used both Python and R to analyze your data and your code demonstration for both were very easy to understand. Your ggplot gave a good visualization of how the CO2 emissions in the U.S. have increased over the years. Overall great job on your presentation!

**Comment by motazb** [comment]
Hey Alex. Nice job with the presentation, I thought this is was really cool data to visualize because of the steep rends in our country's CO2 emissions. I think what would also be cool is a graph of the total CO2 produced so far versus the year. So, for every year, you would have to add all of the produced CO2 emissions from every year prior to it. Although that may too extreme of an exponential graph I would be interested to see it. Good job overall with the project and presentation!

**Comment by dylanreadel** [comment]
This is such an important topic and is at the heart of understanding much of climate change and the effects it has on society. Considering recent events, I am interested in the potential for your code to be used to show how carbon dioxide emissions will be affected by the mass lockdown happening worldwide. There is going to be a significant reduction in transportation and electricity since stores are closing, so your code could visualize the decrease in emissions related to this pandemic.

**Comment by goharmihranian** [comment]
Hi Alex! I really enjoyed your choice in topic, since CO2 emissions are so so important and analyzing data on them can have such a big impact on how we move forward. I also loved how you compared so many different variables and graphed all of them to really be able to compare. I have to agree with Dylan, we've seen so much decrease in CO2 emissions just in China after their lockdown and seeing how it'll affect the rest of the world as we move forward will be really cool to analyze. Great job!

**Comment by chausteven** [comment]
Hey Alex, I noticed that at the beginning of the lightning talk as you were explaining your dataset that there were a couple of columns on the right side that had 0's for the data but no header. I was just wondering why these columns had 0's instead of being completely blank, and if that affected any of your code when you were working with the dataset? Other than that great job with creating such readable and informative graphs!
